version: "3.4"

services:
    postgres: 
        environment: 
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=${ADMIN_PASSWORD}
        image: postgres:14
        restart: always
        volumes: 
            - "./postgres/init:/docker-entrypoint-initdb.d/"
            - "./postgres/data:/var/lib/postgresql/data"
            - "/etc/localtime:/etc/localtime:ro"

    nextcloud: 
        depends_on: 
          - postgres
        image: nextcloud:latest
        restart: always
        environment: 
            - POSTGRES_DB=nextcloud
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=${ADMIN_PASSWORD}
            - POSTGRES_HOST=postgres
            - REDIS_HOST=redis
            - REDIS_HOST_PORT=6379
            - NEXTCLOUD_ADMIN_USER=${ADMIN_LOGIN}
            - NEXTCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
            - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN}
            - SMTP_HOST=172.17.0.1
            - SMTP_PORT=25
            - SMTP_AUTHTYPE=PLAIN
            - MAIL_FROM_ADDRESS=[DOMAIN]@vm.elestio.app
            - PHP_MEMORY_LIMIT=512M
            - PHP_UPLOAD_LIMIT=512M
        ports:
            - 172.17.0.1:21000:80
        volumes: 
            - "./nextcloud/data:/var/www/html/data"
            - "./nextcloud/config:/var/www/html/config"
            - "./nextcloud/themes:/var/www/html/themes"
            - "./nextcloud/custom_apps:/var/www/html/custom_apps"
            - "/etc/localtime:/etc/localtime:ro"

    redis:
        image: redis:latest
        restart: always

    collabora:
        image: collabora/code:latest
        cap_add: 
            - MKNOD
        environment: 
            - domain=${DOMAIN}
            - username=${ADMIN_LOGIN}
            - password=${ADMIN_PASSWORD}
        ports:
            - 1001:9980
        restart: always
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
