version: "2"

services:
  db:
    image: elestio/mysql:8.0
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ADMIN_PASSWORD}
      - MYSQL_PASSWORD=${ADMIN_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: elestio/nextcloud:latest
    restart: always
    ports:
      - 172.17.0.1:22000:80
    links:
      - db
    volumes:
      - ./nextcloud:/var/www/html
      - ./apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=${ADMIN_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=${DOMAIN}
      - OVERWRITEPROTOCOL=https

  cron:
    image: elestio/nextcloud:latest
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
      - ./apps:/var/www/html/custom_apps
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
    entrypoint: /cron.sh

  coturn:
    image: coturn/coturn:latest
    restart: always
    ports:
      - "3478:3478"
      - "3478:3478/udp"
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
